#!/usr/bin/env python3
"""Convert Cookie-Editor JSON export (list of cookies) to Netscape cookies.txt.

Works for yt-dlp --cookies.

Input: JSON array of objects containing at least: name, value, domain, path, secure, httpOnly, session, expirationDate.
"""

import argparse
import json
import os
import time


def to_bool_flag(v: bool) -> str:
    return "TRUE" if v else "FALSE"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="in_path", default="/root/bilibili_cookies.json", help="Path to cookie JSON export (default: /root/bilibili_cookies.json)")
    ap.add_argument("--out", dest="out_path", default="/root/.openclaw/workspace/tmp/bili/bilibili_cookies.txt", help="Output cookies.txt path (default: workspace tmp)")
    args = ap.parse_args()

    with open(args.in_path, "r", encoding="utf-8") as f:
        cookies = json.load(f)

    if not isinstance(cookies, list):
        raise SystemExit("Input must be a JSON array")

    now = int(time.time())
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by cookie_json_to_netscape.py for yt-dlp",
    ]

    count = 0
    for c in cookies:
        if not isinstance(c, dict):
            continue
        name = c.get("name")
        value = c.get("value")
        domain = c.get("domain")
        if not name or value is None or not domain:
            continue

        include_subdomains = domain.startswith(".")
        path = c.get("path") or "/"
        secure = bool(c.get("secure"))
        session = bool(c.get("session"))
        exp = c.get("expirationDate")

        if session:
            expiry = 0
        else:
            try:
                expiry = int(float(exp)) if exp else now + 86400
            except Exception:
                expiry = now + 86400

        http_only = bool(c.get("httpOnly"))
        domain_field = ("#HttpOnly_" + domain) if http_only else domain

        # domain \t include_subdomains \t path \t secure \t expiry \t name \t value
        lines.append(
            "\t".join(
                [
                    domain_field,
                    to_bool_flag(include_subdomains),
                    path,
                    to_bool_flag(secure),
                    str(expiry),
                    str(name),
                    str(value),
                ]
            )
        )
        count += 1

    os.makedirs(os.path.dirname(os.path.abspath(args.out_path)), exist_ok=True)
    with open(args.out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")

    try:
        os.chmod(args.out_path, 0o600)
    except Exception:
        pass

    print(f"wrote {count} cookies -> {args.out_path}")


if __name__ == "__main__":
    main()
