#!/usr/bin/env python3
import json
import os
import random
import re
import shutil
import subprocess
import time
from pathlib import Path

WORKSPACE = Path('/root/.openclaw/workspace')
STATE_DIR = WORKSPACE / '.openclaw' / 'rebang-douyin'
STATE_FILE = STATE_DIR / 'state.json'
LOG_FILE = STATE_DIR / 'run.log'
TMP_DIR = STATE_DIR / 'tmp'

REBANG_URL = 'https://rebang.today/?tab=douyin'

AGENT_BROWSER = 'agent-browser'
AB_SESSION = 'rebang'

YTDLP = '/root/.local/bin/yt-dlp'
VIDEO_POST_JS = '/root/.openclaw/workspace/skills/twitter-post/scripts/video_post.js'

MAX_USED_KEEP = 1000

HASHTAGS = ['#Douyin', '#Trending', '#China', '#Hot', '#viral']


def log(msg: str):
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    ts = time.strftime('%Y-%m-%d %H:%M:%S', time.localtime())
    with LOG_FILE.open('a', encoding='utf-8') as f:
        f.write(f'[{ts}] {msg}\n')


def run(cmd, timeout=600):
    p = subprocess.run(cmd, text=True, capture_output=True, timeout=timeout)
    return p.returncode, p.stdout.strip(), p.stderr.strip()


def load_state():
    if not STATE_FILE.exists():
        return {"used": []}
    try:
        return json.loads(STATE_FILE.read_text(encoding='utf-8'))
    except Exception:
        return {"used": []}


def save_state(st):
    st['used'] = st.get('used', [])[-MAX_USED_KEEP:]
    STATE_DIR.mkdir(parents=True, exist_ok=True)
    STATE_FILE.write_text(json.dumps(st, ensure_ascii=False, indent=2), encoding='utf-8')


def scrape_candidates():
    # open and extract (videoUrl, title) pairs
    run([AGENT_BROWSER, '--session', AB_SESSION, 'open', REBANG_URL], timeout=120)
    run([AGENT_BROWSER, '--session', AB_SESSION, 'wait', '8000'], timeout=120)

    js = r"""
(() => {
  // Each item is rendered as several links; the video link is https://www.douyin.com/video/<id>
  // Title is typically in an adjacent <a> with longer text.
  const rows = [];
  const anchors = Array.from(document.querySelectorAll('a'));
  for (let i = 0; i < anchors.length; i++) {
    const a = anchors[i];
    const href = a.href || '';
    if (!href.includes('www.douyin.com/video/')) continue;
    // find the next anchor that looks like a title (longer text, not @handle, not duration)
    let title = '';
    for (let j = i+1; j < Math.min(i+8, anchors.length); j++) {
      const t = (anchors[j].textContent || '').trim();
      if (!t) continue;
      if (t.startsWith('@')) continue;
      if (/^\d{2}:\d{2}/.test(t)) continue;
      if (t.length >= 6) { title = t; break; }
    }
    rows.push({ url: href, title });
  }
  // de-dup by url
  const seen = new Set();
  const out = [];
  for (const r of rows) {
    if (seen.has(r.url)) continue;
    seen.add(r.url);
    out.push(r);
  }
  return JSON.stringify(out.slice(0, 50));
})()
"""
    code, out, err = run([AGENT_BROWSER, '--session', AB_SESSION, 'eval', js], timeout=120)
    if code != 0:
        raise RuntimeError(f'agent-browser eval failed: {err or out}')

    out = out.strip()
    # agent-browser wraps strings in quotes sometimes; try to parse
    if out.startswith('"') and out.endswith('"'):
        out = json.loads(out)
    data = json.loads(out)
    return data


def _cookies_from_agent_browser(url: str, out_path: Path) -> bool:
    """Get fresh cookies by loading the URL in agent-browser, then export to Netscape cookie file."""
    # Use a dedicated session to avoid clobbering other sessions
    sess = 'dycookies'
    run([AGENT_BROWSER, '--session', sess, 'open', url], timeout=120)
    run([AGENT_BROWSER, '--session', sess, 'wait', '8000'], timeout=120)
    code, out, err = run([AGENT_BROWSER, '--session', sess, 'cookies'], timeout=120)
    # Don't close; daemon reuse is fine
    if code != 0 or not out:
        log(f'cookies export failed: {err or out}')
        return False

    lines = [l.strip() for l in out.splitlines() if l.strip()]
    # agent-browser prints first line like: =douyin.com
    domain = None
    if lines and lines[0].startswith('='):
        domain = lines[0][1:]
        lines = lines[1:]

    # Write Netscape cookie file
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open('w', encoding='utf-8') as f:
        f.write('# Netscape HTTP Cookie File\n')
        f.write('# generated by rebang_douyin_video_post.py\n')
        for l in lines:
            if '=' not in l:
                continue
            name, value = l.split('=', 1)
            name = name.strip()
            value = value.strip()
            if not name:
                continue
            d = domain or '.douyin.com'
            include_sub = 'TRUE' if d.startswith('.') else 'FALSE'
            path = '/'
            secure = 'TRUE'
            expires = '0'
            f.write('\t'.join([d, include_sub, path, secure, expires, name, value]) + '\n')
    return True


def download_video(url: str, out_dir: Path) -> Path | None:
    out_dir.mkdir(parents=True, exist_ok=True)
    template = str(out_dir / 'video.%(ext)s')

    cookies_txt = out_dir / 'cookies.txt'
    if not _cookies_from_agent_browser(url, cookies_txt):
        log('could not obtain fresh cookies')
        return None

    cmd = [YTDLP, '--cookies', str(cookies_txt), '-f', 'bv*+ba/b', '--merge-output-format', 'mp4', '-o', template, url]
    code, out, err = run(cmd, timeout=900)
    if code != 0:
        log(f'yt-dlp failed: {err[:300] or out[:300]}')
        return None
    for p in out_dir.iterdir():
        if p.suffix.lower() in ('.mp4', '.mkv', '.webm'):
            return p
    return None


def craft_tweet(title: str) -> str:
    """Use agent to generate human-like tweet for video"""
    try:
        prompt = open(f"{str(WORKSPACE)}/prompts/x_post_prompt.txt").read().replace("{SOURCE_TEXT}", (title or "一条有趣的抖音视频")[:500])
        r = subprocess.run(
            ['openclaw', 'agent', '--session-id', 'x-video-human', '--thinking', 'minimal', '--json', '--message', prompt],
            capture_output=True, text=True, timeout=120
        )
        if r.returncode == 0:
            import json as _json
            text = _json.loads(r.stdout).get('result', {}).get('payloads', [{}])[0].get('text', '').strip().strip('"').strip("'")
            if text:
                return text[:260]
    except:
        pass
    # Fallback
    title = re.sub(r'\s+', ' ', (title or '').strip())
    return (title[:200] if title else "")[:260]


def post_video(video_path: Path, text: str):
    code, out, err = run(['node', VIDEO_POST_JS, str(video_path), text], timeout=900)
    if code != 0:
        return False, (out or err)
    return True, out


def main():
    if not Path(YTDLP).exists():
        log('yt-dlp missing at /root/.local/bin/yt-dlp')
        return 1

    st = load_state()
    used = set(st.get('used', []))

    try:
        candidates = scrape_candidates()
    except Exception as e:
        log(f'scrape failed: {e}')
        return 1

    if not candidates:
        log('no candidates')
        return 1

    TMP_DIR.mkdir(parents=True, exist_ok=True)

    for c in candidates:
        url = c.get('url')
        title = c.get('title', '')
        if not url or url in used:
            continue

        # Clean temp dir
        if TMP_DIR.exists():
            shutil.rmtree(TMP_DIR)
        TMP_DIR.mkdir(parents=True, exist_ok=True)

        log(f'trying {url} title={title[:40]}')
        video = download_video(url, TMP_DIR)
        if not video:
            continue

        # size guard (video upload limits vary; be conservative)
        if video.stat().st_size > 450 * 1024 * 1024:
            log('skip too large')
            continue

        tweet = craft_tweet(title)
        ok, resp = post_video(video, tweet)
        if ok:
            used.add(url)
            st['used'] = list(used)
            save_state(st)
            log(f'posted: {resp}')
            print(resp)
            return 0
        else:
            log(f'post failed: {resp[:300]}')

    log('no post succeeded')
    return 1


if __name__ == '__main__':
    raise SystemExit(main())
